
# BALANCE: tweaking these numbers will make or break game balance

INITIAL_MONEY: int = 30
DEMON_INITIAL_HEALTH: int = 10
DEMON_INITIAL_ATTACK_POWER: int = 10
MERCENARY_INITIAL_HEALTH: int = 20
MERCENARY_ATTACK_POWER: int = 10
MERCENARY_PRICE: int = 20
DEMON_SPAWNER_RELOAD_TURNS: int = 10
DEMON_HEALTH_INCREASE_PER_SPAWN: int = 5
DEMON_ATTACK_POWER_INCREASE_PER_SPAWN: int = 3
PLAYER_BASE_INITIAL_HEALTH = 200
MAX_TURNS = 300

# Tower stats
TOWER_PRICE_PERCENT_INCREASE_PER_BUY = 10

HOUSE_MAX_COOLDOWN: int = 6
HOUSE_BASE_PRICE: int = 10
HOUSE_RANGE: int = 0
HOUSE_MONEY_PRODUCED: int = 12

CANNON_MAX_COOLDOWN: int = 5
CANNON_BASE_PRICE: int = 10
CANNON_RANGE: int = 3
CANNON_DAMAGE: int = 5

MINIGUN_MAX_COOLDOWN: int = 0
MINIGUN_BASE_PRICE: int = 15
MINIGUN_RANGE: int = 3
MINIGUN_DAMAGE: int = 2

CROSSBOW_MAX_COOLDOWN: int = 4
CROSSBOW_BASE_PRICE: int = 8
CROSSBOW_RANGE: int = 4
CROSSBOW_DAMAGE: int = 4

CHURCH_MAX_COOLDOWN: int = 10
CHURCH_BASE_PRICE: int = 30
CHURCH_RANGE: int = 2
CHURCH_BUFF_DAMAGE: int = 7
CHURCH_BUFF_HEALTH: int = 10